### ISSUE TITLE
Review: Props taking objects with optional properties

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#10]
`dialog.transitionDuration` takes a an object with optional `enter` and `exit` properties and is implemented like this:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Props.fs#L962

Does that approach make sense?

**Comment by Zaid-Ajaj** [comment]
> Does that approach make sense?

If you happen to use this pattern a bunch of times in your code base, it might be easier if you made a helper function that takes `(string * Option<'a>) list` and creates an object literal from it. That function doesn't need to be inlined because it would be defined once and re-used throughout the code

**Comment by cmeeren** [comment]
Thanks! Since it's generated, I don't care that much about the actual code. I currently have a helper to generate them, so it looks like this:

https://github.com/cmeeren/Feliz.MaterialUI/blob/8ba1a2d212d4c396edd72c811324bda965bcc27a/src/Feliz.MaterialUI.Generator/Props.fs#L406-L414

In this issue I was thinking about the resulting user-facing API. Does that look good? I personally think it works very well.

PS, the generator code (as a whole) is horrible. Please don't judge, it was hacked and experimented together 😆

**Comment by cmeeren** [comment]
Closing this because I'm happy with it. Feel free to disagree.
