### ISSUE TITLE
Review: Erasing and inlining

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#12]
I have followed the rule of thumb that non-trivial functions are not inlined, and that types are only erased if all members are inlined.

For example, here is a function that is not inlined (and thus its declaring type is not erased):

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Props.fs#L154

Does that make sense?

**Comment by Zaid-Ajaj** [comment]
I believe it is OK for an implementation but I am not sure about being consistent now that the user has to use names parameters for this function. You could also use overloads of anonymous records:
```fs
[<Erase>]
type backdrop =

  member inline transitionDuration(duration: {| appear: int |}) = 
    Interop.mkAttr "transitionDuration" (toPlainJsObj duration)

  member inline transitionDuration(duration: {| appear: int; enter: int |}) = 
    Interop.mkAttr "transitionDuration" (toPlainJsObj duration)
```
Though Fable/REPL seem to fail to compile different overloads for these functions, see [Fable/Issue#1891](https://github.com/fable-compiler/Fable/issues/1891)

**Comment by cmeeren** [comment]
IMHO optional params is an idiomatic way to solve this. Keep in mind that it's only used if setting individual durations; there is also an overload taking a single number (corresponding to the official MUI signature).

Also, if using anonymous records, I would have to add any possible combination - for three params, that'd be 7 overloads, and for the below prop it's completely out of the question:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Props.fs#L5295

**Comment by Zaid-Ajaj** [comment]
I think a lot of these design choices will come down to a number of things:
 - Completeness: how much of the API is covered correctly covered
 - Ease of use

I think instead of guessing what the best choice is, it is better to make a sample application (docs app?) in this repo and trying things out, a lot of them and seeing which things are limited in use and which things are hard to use (things that are hard to use or require some extra mental overhead will most likely be ignored) 

Yeah probably an anonymous record isn't the best choice, TBH I don't what is and so I suggest we start actually using the library to see for ourselves ;)

**Comment by cmeeren** [comment]
Yep. That's what I have been doing with [the feliz branch here](https://github.com/cmeeren/fable-elmish-electron-material-ui-demo/tree/feliz).

**Comment by cmeeren** [comment]
Closing this because the original question was answered.
