### ISSUE TITLE
Some components have {component}.children but others have to fall back to prop.children?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [cmeeren/Feliz.MaterialUI#20]
I think it would be clean and consistent if `children` prop was added to all components so that you don't get this:
```fs
let render (state: State) (dispatch: Msg -> unit) =
  Mui.container [
    container.maxWidth.xl
    container.children [
      Mui.card [
        card.raised false 
        prop.children [ // <-- this line
          Mui.cardHeader [ ]
          Mui.cardContent [ ] 
        ]
      ]
    ]
  ]
```
but instead 
```fs
let render (state: State) (dispatch: Msg -> unit) =
  Mui.container [
    container.maxWidth.xl
    container.children [
      Mui.card [
        card.raised false 
        card.children [ // much better
          Mui.cardHeader [ ]
          Mui.cardContent [ ] 
        ]
      ]
    ]
  ]
```

**Comment by cmeeren** [comment]
Thanks, this should be fixed in the MUI docs: https://github.com/mui-org/material-ui/issues/17674

**Comment by cmeeren** [comment]
Actually, there is no problem here. As indicated by https://github.com/mui-org/material-ui/issues/17674#issuecomment-537821255, many MUI components forward their props to root elements. This is explicitly documented in the API, and also in the Feliz.MaterialUI bindings:

https://github.com/cmeeren/Feliz.MaterialUI/blob/8ba1a2d212d4c396edd72c811324bda965bcc27a/src/Feliz.MaterialUI/Mui.fs#L28-L31

The semantically correct usage is therefore:

```f#
let render (state: State) (dispatch: Msg -> unit) =
  Mui.container [
    container.maxWidth.xl
    container.children [
      Mui.card [
        card.raised false 
        paper.children [
          Mui.cardHeader [ ]
          Mui.cardContent [ ] 
        ]
      ]
    ]
  ]
```

**Comment by Zaid-Ajaj** [comment]
> The semantically correct usage is therefore

Although it might be the "correct" usage, the propagation of children into the very top container type is (and should be) an implementation detail: it will confuse many users having to know the specifics of this.

My point is that we want to make looking for things (discoverability) as simple as possible without having to look in too many places, in this case when you are using `Mui.card` it would be great to add the things you will most likely use in the `card` type as well -> children

This also applies to things like `button.onClick` and `button.text` for `Mui.button`. Yes I know it is not entirely needed but it makes the lives of devs easier much much easier

**Comment by cmeeren** [comment]
I assume you don't want each component to separately define ALL the props of its root elements, and its root elements' root elements, and so on, all the way to native elements (essentially replicating the entire Feliz API for all components).

Under that assumption:
* How can we determine which props to duplicate?
* Since we're duplicating some props but not others, is the inconsistency something we can live with, or is that confusing for devs in itself? (E.g., "why does component X have prop Y when it's not listed in the MUI API?", or "why does component X have prop Y but not Z replicated from its root element?")

I like discoverability as much as the next dev (hence my working on Feliz.MaterialUI), but at the moment I'm inclined to think that when using Material-UI, it's simply required knowledge (and easily accessible) which components will forward props to which other components. It is certainly required when working with MUI in JS/TS.

That said, if we can improve upon that without too many caveats, I'm open to that. Furthermore, since things are auto-generated, it wouldn't be too hard to insert prop X from component Y into component Z, too, as long as we have pre-defined lists of which props to insert (or can infer that from the source docs somehow). It would be a bit of work to implement it, but once implemented, it would "just work". I would also need to make a solution for inserting native Feliz props.

**Comment by Zaid-Ajaj** [comment]
> I like discoverability as much as the next dev (hence my working on Feliz.MaterialUI), but at the moment I'm inclined to think that when using Material-UI, it's simply required knowledge (and easily accessible) which components will forward props to which other components. It is certainly required when working with MUI in JS/TS.

When working with Mui in JS, you write the code
```jsx
<Card>
  <CardHeader>Title</CardHeader>
  <CardContent>Content</CardContent>
</Card>
```
You don't think about children being forwarded to paper - I certainly don't as I just learned this detail about it and if I had to learn and *remember* where what goes, then it already too high of an entry barrier for me 

> I assume you don't want each component to separately define ALL the props of its root elements, and its root elements' root elements, and so on, all the way to native elements (essentially replicating the entire Feliz API for all components).

That would actually be ideal, if it doesn't add to the bundle size and can be added to the generator, then I am all in for it. I think of Mui as a UI library that worked around inheritance by forwarding the props up to the parent but many UI libraries allow you to set properties of the specific element (i.e. text of button) because it inherits from a generic control which has text as well, since we can't use inheritence here (I have no idea how in any case) then duplicating the code might be a solution

> How can we determine which props to duplicate

Can we hard code the inheritance hierarchy in a list and use that as a starting point? it should be doable, there aren't that many components after all

**Comment by cmeeren** [comment]
> When working with Mui in JS, you write the code [...] You don't think about children being forwarded to paper

You're right, `children` is special.

> That would actually be ideal, if it doesn't add to the bundle size and can be added to the generator, then I am all in for it.

Hm. Something to actually consider. 🤔 But replicating the entire Feliz UI? Then I'd have to re-generate every time Feliz changed, too. Added maintenance burden.

Side note: Since you're in favour of this, why not have the same kind of API for Feliz? There are, after all, several element-specific props for native components, too. (We've touched on this in a few issues in the Feliz repo.)

> since we can't use inheritence here (I have no idea how in any case)

Check out the [Elmish.WPF.Dynamic usage](https://github.com/cmeeren/Elmish.WPF.Dynamic#how-is-it-used). Something like that might work, but I'm not sure if that makes it a more friendly API. It would also not be immediately compatible with vanilla Fable.React, though a simple helper function could solve that. Feel free to experiment!

> Can we hard code the inheritance hierarchy in a list and use that as a starting point? it should be doable, there aren't that many components after all

That is certainly possible, though if feasible I'd rather just pick the hierarchy from the previously mentioned prop forwarding message.

**Comment by Zaid-Ajaj** [comment]
> Then I'd have to re-generate every time Feliz changed, too

Feliz props are static, they only change when the html specs change so that is not a big deal

> Since you're in favour of this, why not have the same kind of API for Feliz?

Unlike elements in third-party libraries, Html elements are not specialized (with some exceptions ofc) so I am not sure this code would make sense
```fs
Html.div [
  div.style [ style.margin 5 ]
  div.children [
    Html.button [
      button.style [ style.padding 10 ]
      button.onClick (fun _ -> printfn "Hello")
      button.text "Click me"
    ]
  ]
]
``` 
Though if I look at it now, it is not bad at all. However, 3rd party libraries would have to consider extending existing props such `button` instead of creating a new type

> Check out the Elmish.WPF.Dynamic usage.

I don't think I like that syntax, it is not as "declarative" as I would like to have it (though this is very subjective) 

> That is certainly possible, though if feasible I'd rather just parse the hierarchy from the previously mentioned prop forwarding message.

If it is possible that would be great, I see a couple of components say: "Any other props supplied will be provided to the root element (native element)" but it is not clear (from my understanding) which element is the native element of that specific component (such as `bottomNavigation` is that `nav` maybe?)

**Comment by cmeeren** [comment]
> Feliz props are static, they only change when the html specs change so that is not a big deal

Assuming the Feliz API is stable, which is might not be. "Can you please add overload X", "you've forgotten prop Y", etc. 😅 

> I see a couple of components say: "Any other props supplied will be provided to the root element (native element)" but it is not clear (from my understanding) which element is the native element of that specific component

Yeah, if it says "native element" then I guess we could just copy the whole Feliz API.

---


Just had a brainwave: Would it work if instead of modules and static types, we have normal classes, and the `button` in `button.style` would just be a previously defined instance of that class (like with CE builders)? Because then we can do inheritance. Something like:

```f#
type paper () =
  member inline __.X ...
  member inline __.Y ...

let paper = paper ()

type card () =
  inherit paper ()
  member inline __.Z ...
  // inherits X and Y

let card = card ()
```

**Comment by Zaid-Ajaj** [comment]
> Would it work if instead of modules and static types, we have normal classes, and the button in button.style would just be a previously defined instance of that class

Looks like that [would work](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcxQFB4DaAPAKJZwDOYAfALp4AuAnuFCHOFgCqtgAUASigBePFCgBbMJIRgsUAJYQky3AH11qABqioAImAQw+8VJlyFy1caibUATT37GAd2Cm8KRu07y9HFy84EIEJORUtAwsbADGcFgAJsECwmISygAW8oo+gfIpoRLSsv7WanZaAFrOjJk4JmZeYD7xSXptyXxQoQTeUAAelHqEnToA3FBjDpNjVXRAA&html=DwCwLgtgNgfAUAAiQ0BTAhgE3s3KKpjoLhgAOAtKgI4CuAlgG4C8ARAMID2AdmKrxQAqATzKpWCAMY8+vNnwAeYAPThoAbkkh0AJwDOhZrTAAzCgA5WOZMFUZsiGwCNOmYdaS2Xb+LbWwgA&css=Q) :wink:

**Comment by cmeeren** [comment]
Well, that solves our problems then, doesn't it? If you do that in Feliz (e.g. a `prop` class) then I can easily derive from the Feliz props.

Heck, you could even easily have component-specific props using that method. As a first step, all component-specific prop classes can derive from a `prop` class containing everything. Then I can start deriving from element-specific prop classes (e.g. `button`), and you can clean up the API where relevant in your own time.

Would the same `[<Erase>]` rules work for non-static classes? I.e., if all members are `inline`, we can erase it, and if not, it must not be erased?

**Comment by cmeeren** [comment]
Another complication for the inheritance stuff: According to https://github.com/mui-org/material-ui/issues/17674#issuecomment-537880347, there are components that don't support all of their "root" props. So this is not a strict inheritance thing anyway.

**Comment by cmeeren** [comment]
It seems that MUI never forwards `children`, so that's a special case. (There may be more special cases for all I know.) https://github.com/mui-org/material-ui/issues/17674#issuecomment-537899691

**Comment by Zaid-Ajaj** [comment]
There is another problem with inheritable prop classes: they cannot be extended with equivalent modules, this doesn't compile 😢 
```fs
open Fable.Core 

[<Erase>]
type paperType() =
  member inline _.X = "one"
  member inline _.Y = "two"

let paper = paperType()

[<Erase>]
type cardType() =
  inherit paperType()
  member inline _.Z = "three"
  
let card = cardType ()

module card = 
  let hello = "whatever"

// card does not have hello definition
let xs = [card.X; card.Y; card.Z; card.hello]
printfn "%A" xs
```

**Comment by cmeeren** [comment]
No, but this does 😄 

```f#
[<Erase>]
type paperType() =
  member inline _.X = "one"
  member inline _.Y = "two"

let paper = paperType()

[<Erase>]
type cardHelloType() =
  member inline _.foo = "whatever"

[<Erase>]
type cardType() =
  inherit paperType()
  let cardHelloType = cardHelloType ()
  member inline _.Z = "three"
  member inline _.hello = cardHelloType
  
let card = cardType ()

// card does not have hello definition
let xs = [card.X; card.Y; card.Z; card.hello.foo]
printfn "%A" xs
```

**Comment by Zaid-Ajaj** [comment]
Nice!

**Comment by cmeeren** [comment]
PS, I'd consider naming the type `paperProps` and `cardProps` etc.

**Comment by cmeeren** [comment]
Regarding my previous comment:

> Heck, you could even easily have component-specific props using that method. As a first step, all component-specific prop classes can derive from a `prop` class containing everything. ~Then I can start deriving from element-specific prop classes (e.g. `button`)~, and you can clean up the API where relevant in your own time.
> 
> **Edit:** That won't work though, because MUI often allows you to change the underlying component (e.g. `paper.component "nav"`). So I have to inherit the whole Feliz prop API anyway, because I don't know at compile time which prop will be used.

In fact, we might yet get it working. We could parametrize the prop types by the root component's prop type, e.g. `paperProps<navProps>`. Then `paperProps` could have a property of type `navProps` that gives access to those props (getting dangerous though, because the prop name might be taken by "real" MUI props later). We could have instances `paper` (default) and `paperWith nav` to instantiate a `paperProps<navProps>` using the default `nav` props instance (perhaps we could also have it set `paper.component "nav"`, though I'm not sure exactly how - perhaps SRTP and a suitable member on all native element prop types?).

Not ideal, but an idea nonetheless.

---

Regarding this previous comment of mine:

> For example, not all components support `children` even though they forward props to a root element that support `children`. So this can not be strictly modelled by inheritance. The question is whether that's a big enough problem to discard this idea.

One workaround is to shadow inherited, unsupported `children` members by implementing a `children` member with an unusable type (e.g. a prop returning a custom `UnsupportedProp` type that can't be used in the DSL).

AFAIK a simple property like that will shadow all method overloads, too.

**Comment by cmeeren** [comment]
Re. the Elmish.WPF.Dynamic syntax: A slightly better syntax in this case may be the following:

```f#
Html.div (fun d ->
  d.style (fun s -> s.margin 5)
  d.children [
    Html.button (fun b ->
      b.style (fun s -> s.padding 10 )
      b.onClick (fun _ -> printfn "Hello")
      b.text "Click me"
    )
  ]
)
```

In other words, the usage is exactly like the current syntax except instead of a prop list, there's an initializer function that gives you the parameter by which you access the props. So you never have to "hunt around" for the correct type/module where the available props are defined.

This may have more benefits in Feliz.MaterialUI than in Feliz. For example, al the `classes` props currently document that you should e.g. `use classes.appBar to specify class names.` That instruction could be moot if one simply did `appBar.classes (fun c -> c.root "foo"; c.positionFixed "bar")`.

In any case, I'm not about to go making this change. Just thought I'd mention id.

**Comment by cmeeren** [comment]
Dang, I just thought of something. With the proposed instance-member syntax, it's not possible to have mixed enum and non-enum props. For example, I can't think of a way to achieve both of following variants:

```f#
popover.anchorOrigin.topLeft
popover.anchorOrigin(10, 20)
```

**Comment by cmeeren** [comment]
Wait a minute... Might we solve this without any inheritance, and instead use module and type aliases? For example:

![image](https://user-images.githubusercontent.com/7766733/66395587-1d94a780-e9d8-11e9-82d2-0d960e836f11.png)

**Comment by cmeeren** [comment]
Man, this issue is proving difficult.

I was hovering over the "commit" button with a completed solution, but figured I'd test it first. And it turns out that I can't use this to inherit enum (module) props, because module aliases are only accessible within a file.

I tried doing this (`menuItem` inherits `listItem` which inherits `buttonBase`):

```f#
[<AutoOpen>]
module InheritanceLevel2 =

  type menuItem = buttonBaseProps

module menuIteml = buttonBaseProps

[<AutoOpen>]
module InheritanceLevel1 =

  type menuItem = listItemProps
  type listItem = buttonBaseProps

module menuItem = listItemProps
module listItem = buttonBaseProps


[<AutoOpen>]
module InheritanceLevel0 =

  type menuItem = menuItemProps
  type listItem = listItemProps
  type buttonBase = buttonBaseProps

module menuItem = menuItemProps
module listItem = listItemProps
module buttonBase = buttonBaseProps
```

This works great for the prop types, but not the modules, whose aliases are not accessible outside this file.

So I'm back to start, really.

**Comment by cmeeren** [comment]
I have an idea I think actually may work.

The only trouble are enum prop modules. Since we can't alias the modules, we can alias the prop types inside the modules instead. Seems that'll have to work. I'll get back with details once I have tried.

**Comment by cmeeren** [comment]
Okay, I made it! 0.4.0 is in the pipeline.

Even just aliasing all inherited enum prop types (e.g. `prop.role`, `prop.transform`), including the documentation for each type, added more then 5500 lines to the props file. So I'm glad I got this working.

Feliz.MaterialUI must then be updated each time a new enum prop type (a new type in the `prop` module) is added to Feliz.

I chose to alias `withType` as `type'` to avoid naming conflicts with potential new MUI props called `withType` (and to be consistent with the rest of the Feliz.MaterialUI API).

Give it a try 😃 

Thanks for pushing me on this until I was too [nerd-sniped](https://www.xkcd.com/356/) to give it up! 😆

**Comment by cmeeren** [comment]
Maaan, now even F# is working against me. It seems I am pushing type aliasing past its limits. 😒

The code is correct and works sometimes (e.g. from the same file, or with project references), but other times (e.g. from another file, or from the 0.4.0 NuGet package) certain random props aren't available.

I think this puts an end to all attempts at "inheritance" for static types using type aliasing. There are three options left:

* Don't do inheritance
* Rewrite Feliz to use instances (with the syntactic drawbacks that has as mentioned in this issue and in https://github.com/Zaid-Ajaj/Feliz/issues/53)
* Duplicate desired props

Again, I have not entirely warmed to duplicating arbitrary (or all) base API props.

**Comment by cmeeren** [comment]
0.5.0 is in the pipeline with MUI prop inheritance (duplication), but no base DOM prop duplication. That should be done on a component-by-component and prop-by-prop basis as desired. I have no immediate plans of adding native `prop` props, but I'm open to suggestions.

**Comment by Zaid-Ajaj** [comment]
I am gonna give 0.5.0 a try very soon and let you know of my findings! Thanks a lot for keeping an open mind for the possible options out there

**Comment by Zaid-Ajaj** [comment]
> This also means I need to test my packages often with the released packages as well, not just the project-referenced ones only

**Comment by Zaid-Ajaj** [comment]
Also I loved the nerd-sniping reference :heart:
