### ISSUE TITLE
How to check bundle size?

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#24]
What is the simplest way I can check the bundle size for any given example usage of the library?

/cc @Zaid-Ajaj

**Comment by Zaid-Ajaj** [comment]
The bundle size itself, as in the number per example, doesn't tell much because it varies depending on the size of the consuming application but if you curious to see what gets inline-compiled or defined once and re-used then it is better to compile the application using fable-splitter like [Feliz does](https://github.com/Zaid-Ajaj/Feliz/blob/master/package.json#L6) which compiles the project into raw babel/es6 modules, this way you can get the the same output (more or less) you get from Fable REPL

**Comment by cmeeren** [comment]
Thanks a lot! I will try that.
