### ISSUE TITLE
How can I add an adornment to a text field?

### ISSUE THREAD

**Issue by halcwb** [cmeeren/Feliz.MaterialUI#44]
I cannot figure out how to add an adornment to a textfield like:

                            Mui.textField [
                                textField.label "First Systolic Blood Pressure"
                                textField.InputProps [
                                    inputAdornment.classes.positionEnd "kg"

                                    prop.children [
                                            Mui.inputAdornment [ 
                                                inputAdornment.position.end'
                                                inputAdornment.variant.standard
                                            ]
                                    ]
                                    
                                ]
                            ]

So I want a text field looking like:

> "Label"
> "Input" kg

**Comment by cmeeren** [comment]
You can find this in the [MUI docs](https://material-ui.com/components/text-fields/):

```js
<TextField
  label="With normal TextField"
  InputProps={{
    endAdornment: <InputAdornment position="end">Kg</InputAdornment>,
  }}
/>
```

This means in Feliz.MaterialUI it would look something like this:

```f#
Mui.textField [
  textField.label "Foo"
  textField.InputProps [
    input.endAdornment (
      Mui.inputAdornment [
        inputAdornment.position.end'
      ]
    )
  ]
]
```

There are three errors in your code:
* `textField.inputProps` are props passed to the `TextField`'s `Input` component. Therefore, it must contain props from the `input` module.
* The `classes` prop is [used to override styles](https://cmeeren.github.io/Feliz.MaterialUI/#usage/classes). In your usage, you are saying that the input adornment element, when `position` is set to `end`, should have `class` set to `kg`.
* `prop.children` shouldn't be used for MUI components. `children` is defined as a prop-specific component for all props that support it (e.g. `textField.children` instead of `prop.children`).

**Comment by halcwb** [comment]
Great, thanks. The mapping from your lib to Material UI, for me, is still a bit challenging. But I think I am getting the gist of it.

**Comment by cmeeren** [comment]
Everything is hard when you don't know it and easy once you have learned it. Let me know if there are things I can add/change in the Feliz.MaterialUI docs to make it better!

**Comment by halcwb** [comment]
Thanks again, it's a real joy to use your library. This is the app I am currently working on: https://github.com/halcwb/PediatricRiskCalculator.git

Any comments on your side are welcome!

**Comment by cmeeren** [comment]
Thanks for the kind words! Happy you're liking it. Unfortunately I don't have the capacity to do general code reviews, but let me know if you have problems or specific questions.
